# Generated by Django 5.0.4 on 2024-07-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=10)),
                ('Subject', models.TextField()),
                ('Exam_Name', models.TextField(max_length=10)),
                ('Total_Questions', models.CharField(max_length=10)),
                ('duration', models.DurationField()),
                ('fullmark', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
