# Generated by Django 5.0.4 on 2024-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('full_marks', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='generate_question',
        ),
    ]
